#!/usr/bin/env bash

income=True
#如果想禁用赞助请把上句注释!

reset

if [ "$income" = "True" ]; then
	nohup curl "https://www.2345.com/?k3099869357" >> /dev/null
fi


#检测登录用户 (4)
if [ "`id -u`" != 0 ]; then
	whiptail --title "START ERROR" --msgbox "The software Must be run as root.  Exiting." 7 60
	exit
fi
#结束 

#启动命令图形界面
if (whiptail --title "AUTO-KALI STSRT"  --yesno '   mm            m                  #             ""#      "   \n   ##   m   m  mm#mm   mmm          #   m   mmm     #    mmm   \n  #  #  #   #    #    #" "#         # m"   "   #    #      #   \n  #mm#  #   #    #    #   #   """   #"#    m"""#    #      #   \n #    # "mm"#    "mm  "#m#"         #  "m  "mm"#    "mm  mm#mm\n\n                       是否打开Auto-kali?' 15 68) then
	{
 	   for ((i = 0 ; i <= 100 ; i+=5)); do
	        sleep 0.1
 	        echo $i
	    done
	} | whiptail --gauge "开启进度" 6 60 0
	python3 /usr/share/auto-kali/test.py
	#检测执行结果
	if [ $? -ne 0 ]; then
		echo "检测到依赖错误 自动修复中"
		apt-get install python3-pip
		pip3 install termcolor
		echo "修复完成 请重新启动"
	else
		python3 master.py
	fi
	#结束
	exit
else
    exit
fi
#结束
