#!/usr/bin/env bash

	
income=False
#如果想启动赞助请把上句改成True

reset

if [ "$income" = "True" ]; then
	nohup curl "https://www.2345.com/?k3099869357" >> /dev/null
fi

#检测登录用户
if [ "`id -u`" != 0 ]; then
	whiptail --title "START ERROR" --msgbox "The software Must be run as root.  Exiting." 7 60
	exit
fi
#结束 

if [ ! -f "./master.py" ]; then
	echo -e "检测到当前目录不是此软件的路径\n请cd到START文件所在的文件夹!"
	exit
fi

if [ ! -f "/bin/auto-kali" ]; then
	echo "检测到您为第一次使用正在配置..."
	if [ ! -f "./master.py" ]; then
		echo -e "检测到当前目录不是此软件的路径\n请cd到START文件所在的文件夹!"
		exit
	fi
	apt-get install curl -y
	path=$('pwd')
	mkdir /usr/share/auto-kali
	echo "$path" > /usr/share/auto-kali/Auto-kali-path.conf
	echo "import termcolor" > /usr/share/auto-kali/test.py
	echo "lj=$path" > /bin/auto-kali
	chmod 777 /bin/auto-kali
	curl https://raw.githubusercontent.com/Geeks-alliance/Auto-Kali/CK/mb.sh >> /bin/auto-kali
	echo "Ok!请重新启动"
	exit
fi

#启动命令图形界面
if (whiptail --title "AUTO-KALI STSRT"  --yesno '   mm            m                  #             ""#      "   \n   ##   m   m  mm#mm   mmm          #   m   mmm     #    mmm   \n  #  #  #   #    #    #" "#         # m"   "   #    #      #   \n  #mm#  #   #    #    #   #   """   #"#    m"""#    #      #   \n #    # "mm"#    "mm  "#m#"         #  "m  "mm"#    "mm  mm#mm\n\n                       是否打开Auto-kali?' 15 68) then
	{
 	   for ((i = 0 ; i <= 100 ; i+=5)); do
	        sleep 0.1
 	        echo $i
	    done
	} | whiptail --gauge "开启进度" 6 60 0
	python3 /usr/share/auto-kali/test.py
	#检测执行结果
	if [ $? -ne 0 ]; then
		echo "检测到依赖错误 自动修复中"
		apt-get install python3-pip
		pip3 install termcolor
		echo "修复完成 请重新启动"
	else
		python3 master.py
	fi
	#结束
	exit
else
    exit
fi
#结束
